### PR TITLE
update to JOSM 12671

### PR DESCRIPTION
**Pull request by don-vip**
This PR is required to run on latest versions of JOSM. Can you please merge it and release a new version? Thanks !

### CODE REVIEW

**Comment by iandees** [comment]
Thanks! I released a new version and updated the JOSM wiki page for plugins.

**Comment by don-vip** [comment]
It seems there's a problem with new release? https://josm.openstreetmap.de/ticket/15205

**Comment by iandees** [comment]
I noticed that… I'll take a look after work. I think the last time I ran into this there was something happening with line endings on the METADATA.inf file in the JAR.

**Comment by don-vip** [comment]
Did you have time to look into this issue?

**Comment by iandees** [comment]
Let's move conversation to https://github.com/iandees/josm-mbtiles/issues/15 for now.

**Pull request merged**
