### PR TITLE
Update to new JOSM API + code cleanup

### PR DESCRIPTION
**Pull request by don-vip**
* update to new FileExporter/FileImporter API
* update to new LayerManager API
* partial update to new AbstractTmsLayer class (TODO)
* remove tabs
* update to latest sqlite-jdbc-3.8.11.2

### CODE REVIEW

**Comment by don-vip** [comment]
This plugin does not compile with latest JOSM for a long time (several months I think). This pull request makes the plugin compile and should allow it to be loaded without error at runtime. However, a probably significant update remain to do in MbtilesTileSource to implement the new mandatory methods inherited from AbstractTMSTileSource.

**Comment by iandees** [comment]
Thanks for doing this Vincent. I'll take a look at what else is needed.

**Comment by iandees** [comment]
@don-vip is there a better class to extend from than `AbstractTMSTileSource` for this sort of thing? It seems odd that a TMS layer would be forced to implement those methods – doesn't TMS assume a single projection?

**Comment by don-vip** [comment]
Mmm I don't know. @wiktorn what do you think?

**Comment by wiktorn** [comment]
I think that it's better to extend `TMSTileSource` instead of `AbstractTMSTileSource`. I guess that MBTiles are using only Mercator projection.

**Comment by don-vip** [comment]
Well it's even simpler to use TMSTileSource directly, no? That's what I just have committed.

**Comment by wiktorn** [comment]
Indeed, just checked original code.

**Comment by don-vip** [comment]
Thanks for merging the PR :) Can you please issue a new release now?

**Comment by iandees** [comment]
I cut a new release and updated the josm wiki.

**Comment by don-vip** [comment]
Thanks! :)

**Pull request merged**
